### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by predator8bit** [f0x52/neo#3]
I'm really happy to see such a simple web client for matrix.
I think the two important features that are missing are: 
1. Guest mode, so people can just pick a nickname and start chatting, like on IRC. 
2. Direct links to specific rooms, which would take the user to the specific chat that was linked, so communities can easily direct people into their own rooms.

**Comment by f0x52** [comment]
I added guest mode to the todo list, 2. was already on there

**Comment by predator8bit** [comment]
Awesome, I see you have 'room invites' on there, does that mean 1on1 PMs too?

**Comment by f0x52** [comment]
Yep, 1on1 PM is just a room with only two people
