### ISSUE TITLE
Doesn't work with Homeserver on subdomain

### ISSUE THREAD

**Issue by 26000** [f0x52/neo#6]
I have a server with federation at https://kotobank.ch/_matrix/federation/v1 and client API at https://matrix.kotobank.ch/_matrix/client/r0. When I log in, it works, but makes many requests to https://kotobank.ch/_matrix/client/r0/joined_rooms, which returns 404 obviously. And the room list doesn't show.

**Comment by f0x52** [comment]
this is part of a different, bigger issue, Neo currently doesn't work with homeservers on subdomains. I'll get a fix out soon

**Comment by f0x52** [comment]
Should be fixed in the latest release

**Comment by 26000** [comment]
Thanks! I'll test later.

**Comment by 26000** [comment]
Works! Sorry for delay in testing.
